//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #define _DBG_BOOL 1
        ///#define _DBG_INT 2
        ///#define _DBG_UINT 3
        ///#define _DBG_FLOAT 4
        ///#define _i2f intBitsToFloat
        ///#define _u2f uintBitsToFloat
        ///const int _dbgStageOffset = &lt;&lt;stage offset&gt;&gt;;
        ///
        ///layout(rgba32f) uniform writeonly imageBuffer _dbgOut;
        ///
        ///int _dbgStore(int idx, vec4 val) {
        ///	imageStore(_dbgOut, _dbgStageOffset + idx, val);
        ///	return ++idx;
        ///}
        ///int _dbgStore(int idx, ivec4 val) {
        ///	return _dbgStore(idx, vec4(_i2f(val.x), _i2f(val.y), _i2f(val.z), _i2f(val.w)));
        ///}
        ///int _dbgStore(int idx, uvec4 val) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbg {
            get {
                return ResourceManager.GetString("dbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string DBG_CLOSE {
            get {
                return ResourceManager.GetString("DBG_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string DBG_OPEN {
            get {
                return ResourceManager.GetString("DBG_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uniform &lt;&lt;debug uniform&gt;&gt;;
        ///uniform &lt;&lt;debug frame&gt;&gt;;
        ///
        ///void _dbgMain() {
        ///	int _dbgIdx = 1;
        ///	&lt;&lt;debug code&gt;&gt;
        ///	_dbgStore(0, ivec2(_dbgIdx-1, _dbgFrame));
        ///}
        ///
        ///void _runMain() {
        ///	&lt;&lt;runtime code&gt;&gt;
        ///}
        ///
        ///void main() {
        ///	if (&lt;&lt;debug condition&gt;&gt;)
        ///		_dbgMain();
        ///	else
        ///		_runMain();
        ///}.
        /// </summary>
        internal static string dbgBody {
            get {
                return ResourceManager.GetString("dbgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgClose {
            get {
                object obj = ResourceManager.GetObject("ImgClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgDbg {
            get {
                object obj = ResourceManager.GetObject("ImgDbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgNew {
            get {
                object obj = ResourceManager.GetObject("ImgNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgOpen {
            get {
                object obj = ResourceManager.GetObject("ImgOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgPick {
            get {
                object obj = ResourceManager.GetObject("ImgPick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRun {
            get {
                object obj = ResourceManager.GetObject("ImgRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgSave {
            get {
                object obj = ResourceManager.GetObject("ImgSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgSaveAll {
            get {
                object obj = ResourceManager.GetObject("ImgSaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgSaveAs {
            get {
                object obj = ResourceManager.GetObject("ImgSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // 0 default #C0C0C0
        ///// 0 identifier #000000
        ///// 0 comment #7F9F00
        ///// 0 operator #6080D0
        ///// 0 punctuation #C0C0C0
        ///// 0 preprocessor #E47426
        ///// 0 number #108030
        ///// 0 string #800000
        ///// 0 char #A03030
        ///// 0 block #0000FF
        ///// 0 folding #FF0000 #FFAAAA
        ///// 1 annotation #0099CC
        ///// 2 command #6666FF
        ///// 3 argument #6633CC
        ///// 4 function #993333
        ///// 5 type #0000FF
        ///// 6 specifications #0000FF
        ///// 7 qualifier #0099CC
        ///// 8 variable #0000FF
        ///// 9 branching #0000FF
        ///[0]buffer|buffer &lt;name&gt;
        ///[0]buffer[2]size|si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.xml.
        /// </summary>
        internal static string WINDOW_SETTINGS_FILE {
            get {
                return ResourceManager.GetString("WINDOW_SETTINGS_FILE", resourceCulture);
            }
        }
    }
}
